namespace: fredericpetit
name: graylog-minimal-conf-containerized
version: 1.0.0
readme: README.md
authors:
  - "Frédéric Petit @fredericpetit"
description: "Ansible role to deploy minimal configuration for Graylog with MongoDB and OpenSearch, containerized."
license: MIT
dependencies: {}
tags:
  - graylog
  - docker
  - mongodb
  - opensearch
  - logging
  - minimal